# The Docker plugin is configured explicitly to allow it to work on both Windows and Linux host machines
# Buildkite assumes that the container uses the same OS as the host machine, which means it uses Windows-specific syntax on Windows hosts
# Given that we want to run in a Linux container regardless of the host OS, various aspects of the plugin are configured explicitly

steps:
  - label: ":lint-roller: Lint"
    plugins:
      - docker#v3.3.0:
          image: "node:10"
          volumes: [".:/workdir"]
          workdir: "/workdir"
          mount-checkout: false
          command: ["/bin/bash", "-c", "npm install tslint && npm run lint"]
    soft_fail: true

  - label: ":hammer: Build"
    plugins:
      - docker#v3.3.0:
          image: "node:10"
          volumes: [".:/workdir"]
          workdir: "/workdir"
          mount-checkout: false
          command: ["/bin/bash", "-c", "npm ci && npm run build"]

  - label: ":crossed_fingers: Test"
    plugins:
      - docker#v3.3.0:
          image: "node:10"
          volumes: [".:/workdir"]
          workdir: "/workdir"
          mount-checkout: false
          command: ["/bin/bash", "-c", "npm install --dev && npm run build-test"]